server:
  port: 8080

spring:
  application:
    name: openai-code-review-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/openai_code_review?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 250130
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lz.server.model.entity
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

internal:
  api-token: openai-code-review-internal-token-2026

logging:
  level:
    com.lz.server: DEBUG
